### PR TITLE
Use Bootstrap to make discussion section match design mock

### PR DESCRIPTION
**Pull request by n-wach**

### CODE REVIEW

**Comment by n-wach** [comment]
This can't be merged until Jay merges his bootstrap.

**Comment by f-camp** [comment]
Please add a screenshot showing the latest changes.

**Comment by n-wach** [comment]
This is still in progress, but will add one when done

**Comment by billie-cat** [comment]
Hey Nathan,
I just wanted to recommend not adding reviewers until the PR is ready to review :)

**Pull request closed without merging**
