### PR TITLE
Update storage setting for the local datastore test configuration.

### PR DESCRIPTION
**Pull request by amuamushu**
There was no storage setting for the datastore, which caused one of the tests to fail.

### CODE REVIEW

**Comment by n-wach** [comment]
Is this done in all other tests? Should it be done?

**Comment by jaysaleh** [comment]
> Is this done in all other tests? Should it be done in them?

It is only done in `TranscriptServletTest.java`

**Comment by n-wach** [comment]
> > Is this done in all other tests? Should it be done in them?
> 
> It is only done in `TranscriptServletTest.java`

Can we expand this PR to add this to every other test?  Because it seems like this is a good thing to do to speed up the tests

**Comment by amuamushu** [comment]
> > > Is this done in all other tests? Should it be done in them?
> > 
> > 
> > It is only done in `TranscriptServletTest.java`
> 
> Can we expand this PR to add this to every other test? Because it seems like this is a good thing to do to speed up the tests

done!

**Review by f-camp — APPROVED** [review]

**Review by jaysaleh — APPROVED** [review]

**Pull request merged**
