### PR TITLE
Combine video, discussion, and transcript

### PR DESCRIPTION
**Pull request by n-wach**
Apologies for the large PR, we're still getting things set up.  After this point we should be able to work on independent branches and have smaller PRs.

EDIT: Please do not review this PR yet. We are planning to have our other, smaller ones merged into master first to make this one smaller. Thank you!

### CODE REVIEW

**Comment by n-wach** [comment]
There are still a few more PRs left to merge into staging:
- [ ] Separate front-end
- [ ] Format transcript
- [ ] Code cleanup
- [ ] Tests(?)

**Comment by amuamushu** [comment]
@googlebot I fixed it.

**Comment by n-wach** [comment]
@googlebot I fixed it.

**Comment by amuamushu** [comment]
@googlebot I fixed it.

**Comment by n-wach** [comment]
I'm going to close this so we can create a new PR of off `cla`

**Pull request closed without merging**
